def read(notations_path):
    """
    This reads a notation.tex file generated by notabene and loads
    the tex definition into a dictionnary. This can be used for
    importing tex definitions in matplotlib figures.
    """
    res = dict()
    for line in open(notations_path, 'r'):
        if line[0] not in ['%', '\n']:
            line = line[13:-1]
            words = line.split('}')
            words[1] = words[1][3:]
            value = '}'.join(words[1:])
            res[words[0]] = value
    return res


